I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script call
    call story #story is the label.
  File "game/story.rpy", line 191, in script
    {nw}"She took a few breathes before sliding open the classroom door."
Exception: Sayer '{nw}' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script call
    call story #story is the label.
  File "game/story.rpy", line 191, in script
    {nw}"She took a few breathes before sliding open the classroom door."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '{nw}' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Doki Doki Detective Club 1.1.2
Sat Jul 27 00:30:28 2024
